### PR TITLE
Fixes major issues with new OkC design. Also adds some questions, and cleans up bower stuff.

### LINKED ISSUE #120: New design, plugin covers "My Details"
Yeah, as the title says, the plugin needs to move a bit farther right.

Thanks!

EDIT: Oh, and the overview with all the categories at the top needs to move a bit farther left.

EIDT2: Hovering over profile pictures and seeing an enlarged version of the photo doesn't work anymore, neither.

### PR DESCRIPTION
**Pull request by EvanCarroll**

### CODE REVIEW

**Comment by EvanCarroll** [comment]
This fixes #120

**Comment by benjaffe** [comment]
@EvanCarroll You just made my weekend! I could hug you.

I'm getting home late tonight, so I'll review this and push the changes by tomorrow.

**Comment by EvanCarroll** [comment]
I don't even know why you review my code. It's always flawless.

**Comment by benjaffe** [comment]
It's cause, from your profile pic, you're apparently only 12 years old.

**Pull request merged**
