### PR TITLE
Fix for recent OKC changes. Fixes #161.

### LINKED ISSUE #161: Plugin not working
Seems like as of this evening the plugin isn't working anymore. It only says "No Results".

### PR DESCRIPTION
**Pull request by tfmorris**
This has only been lightly tested and I haven't made any attempt to preserve backward compatibility, which may be necessary if this is a rolling update like they often do, but it does seem to fix the main problems.

### CODE REVIEW

**Comment by benjaffe** [comment]
Fantastic!! I'll test this out tonight and release if all is well.

**Comment by benjaffe** [comment]
Releasing it! Thank you Tom!

**Comment by tfmorris** [comment]
Hi Ben. Did you test the onOwnProfile leg of things? I wasn't sure how that worked, so wasn't able to test it. If you did test it and it's OK, you can remove the obsolete TODO.

I also wasn't sure if this change had been rolled out globally by OKCupid. I'm assuming that the lack of any backward compatibility code means that it has, correct?

**Comment by benjaffe** [comment]
To be honest, I don't remember how that worked UI-wise! I think it may have been more relevant on a previous version of the site, so that's just legacy code.

What should really happen is the plugin should be largely rewritten. I don't foresee myself having enough time to do it. 

Thank you for your work on this! And by the way, If this is a project you're interested in working on, I will gladly test out and release changes you make.

**Pull request closed without merging**
